import java.util.Random;

import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public class RandNote extends Main{
	public void randNotes(){
		
		Random rand = new Random();
		int  n = rand.nextInt(12);
		String note = "";
		System.out.println(n);	
		
		switch (n){
			case 0: note = "DL";
			Image transposedNoteDL = new Image("D_Lower_Clef.png");
			ImageView DL = new ImageView();
			DL.setImage(transposedNoteDL);
			break;
			case 1: note = "EL";
			Image transposedNoteEL = new Image("E_Lower_Clef.png");
			ImageView EL = new ImageView();
			EL.setImage(transposedNoteEL);
			break;
			case 2: note = "FL";
			Image transposedNoteFL = new Image("F_Lower_Clef.png");
			ImageView FL = new ImageView();
			FL.setImage(transposedNoteFL);
			break;
			case 3: note = "GL";
			Image transposedNoteGL = new Image("G_Lower_Clef.png");	
			ImageView GL = new ImageView();
			GL.setImage(transposedNoteGL);
			break;
			case 4: note = "AL";
			Image transposedNoteAL = new Image("A_Lower_Clef.png");
			ImageView AL = new ImageView();
			AL.setImage(transposedNoteAL);
			break;
			case 5: note = "BL";
			Image transposedNoteBL = new Image("B_Lower_Clef.png");	
			ImageView BL = new ImageView();
			BL.setImage(transposedNoteBL);
			break;
			case 6: note = "CL";
			Image transposedNoteCL = new Image("C_Lower_Clef.png");	
			ImageView CL = new ImageView();
			CL.setImage(transposedNoteCL);
			break;
			case 7: note = "DM";
			Image transposedNoteDM = new Image("D_Middle_Clef.png");
			ImageView DM = new ImageView();
			DM.setImage(transposedNoteDM);
			break;
			case 8: note = "EM";
			Image transposedNoteEM = new Image("E_Middle_Clef.png");
			ImageView EM = new ImageView();
			EM.setImage(transposedNoteEM);
			break;
			case 9: note = "FM";
			Image transposedNoteFM = new Image("F_Middle_Clef.png");		
			ImageView FM = new ImageView();
			FM.setImage(transposedNoteFM);
			break;
			case 10: note = "GM";
			Image transposedNoteGM = new Image("G_Middle_Clef.png");
			ImageView GM = new ImageView();
			GM.setImage(transposedNoteGM);
			break;
			case 11: note = "AM";
			Image transposedNoteAM = new Image("A_Middle_Clef.png");
			ImageView AM = new ImageView();
			AM.setImage(transposedNoteAM);
			break;
			case 12: note = "BM";
			Image transposedNoteBM = new Image("B_Middle_Clef.png");
			ImageView BM = new ImageView();
			BM.setImage(transposedNoteBM);
			break;
			case 13: note = "CM";
			Image transposedNoteCM = new Image("C_Middle_Clef.png");
			ImageView CM = new ImageView();
			CM.setImage(transposedNoteCM);
			break;
			case 14: note = "DU";
			Image transposedNoteDU = new Image("D_Upper_Clef.png");
			ImageView DU = new ImageView();
			DU.setImage(transposedNoteDU);
			break;
			case 15: note = "EU";
			Image transposedNoteEU = new Image("E_Upper_Clef.png");	
			ImageView EU = new ImageView();
			EU.setImage(transposedNoteEU);
			break;
			case 16: note = "FU";
			Image transposedNoteFU = new Image("F_Upper_Clef.png");	
			ImageView FU = new ImageView();
			FU.setImage(transposedNoteFU);
			break;
			case 17: note = "GU";
			Image transposedNoteGU = new Image("G_Upper_Clef.png");		
			ImageView GU = new ImageView();
			GU.setImage(transposedNoteGU);
			break;
			case 18: note = "AU";
			Image transposedNoteAU = new Image("A_Upper_Clef.png");	
			ImageView AU = new ImageView();
			AU.setImage(transposedNoteAU);
			break;
			case 19: note = "BU";
			Image transposedNoteBU = new Image("B_Upper_Clef.png");	
			ImageView BU = new ImageView();
			BU.setImage(transposedNoteBU);
			break;
			case 20: note = "CU";
			Image transposedNoteCU = new Image("C_Upper_Clef.png");	
			ImageView CU = new ImageView();
			CU.setImage(transposedNoteCU);
			break;
			case 21: note = "DH";
			Image transposedNoteDH = new Image("D_High_Clef.png");		
			ImageView DH = new ImageView();
			DH.setImage(transposedNoteDH);
			break;
			case 22: note = "EH";
			Image transposedNoteEH = new Image("E_High_Clef.png");	
			ImageView EH = new ImageView();
			EH.setImage(transposedNoteEH);
			break;
			case 23: note = "FH";
			Image transposedNoteFH = new Image("F_High_Clef.png");	
			ImageView FH = new ImageView();
			FH.setImage(transposedNoteFH);
			break;
			case 24: note = "GH";
			Image transposedNoteGH = new Image("G_High_Clef.png");
			ImageView GH = new ImageView();
			GH.setImage(transposedNoteGH);
			break;
		}
	}
}
