package pitches;

public class PitchBuilder {

	private String selectedPitch;	
	
	public String randomPitch(){
		int n = (int)(Math.random() * 58 + 1); // Random number 1-58 inclusive, each number will be used in a switch statement to execute code for pitch it identifies
		
		switch(n){
		case 1: selectedPitch = "D_Natural_1";
		break;
		case 2: selectedPitch = "D_Sharp_1";
		break;
		case 3: selectedPitch = "E_Flat_1";
		break;
		case 4: selectedPitch = "E_Natural_1";
		break;
		case 5: selectedPitch = "F_Natural_1";
		break;
		case 6: selectedPitch = "F_Sharp_1";
		break;
		case 7: selectedPitch = "G_Flat_1";
		break;
		case 8: selectedPitch = "G_Natural_1";
		break;
		case 9: selectedPitch = "G_Sharp_1";
		break;
		case 10: selectedPitch = "A_Flat_1";
		break;
		case 11: selectedPitch = "A_Natural_1";
		break;
		case 12: selectedPitch = "A_Sharp_1";
		break;
		case 13: selectedPitch = "B_Flat_1";
		break;
		case 14: selectedPitch = "B_Natural_1";
		break;
		case 15: selectedPitch = "C_Natural_2";
		break;
		case 16: selectedPitch = "C_Sharp_2";
		break;
		case 17: selectedPitch = "D_Flat_2";
		break;
		case 18: selectedPitch = "D_Natural_2";
		break;
		case 19: selectedPitch = "D_Sharp_2";
		break;
		case 20: selectedPitch = "E_Flat_2";
		break;
		case 21: selectedPitch = "E_Natural_2";
		break;
		case 22: selectedPitch = "F_Natural_2";
		break;
		case 23: selectedPitch = "F_Sharp_2";
		break;
		case 24: selectedPitch = "G_Flat_2";
		break;
		case 25: selectedPitch = "G_Natural_2";
		break;
		case 26: selectedPitch = "G_Sharp_2";
		break;
		case 27: selectedPitch = "A_Flat_2";
		break;
		case 28: selectedPitch = "A_Natural_2";
		break;
		case 29: selectedPitch = "A_Sharp_2";
		break;
		case 30: selectedPitch = "B_Flat_2";
		break;
		case 31: selectedPitch = "B_Natural_2";
		break;
		case 32: selectedPitch = "C_Natural_3";
		break;
		case 33: selectedPitch = "C_Sharp_3";
		break;
		case 34: selectedPitch = "D_Flat_3";
		break;
		case 35: selectedPitch = "D_Natural_3";
		break;
		case 36: selectedPitch = "D_Sharp_3";
		break;
		case 37: selectedPitch = "E_Flat_3";
		break;
		case 38: selectedPitch = "E_Natural_3";
		break;
		case 39: selectedPitch = "F_Natural_3";
		break;
		case 40: selectedPitch = "F_Sharp_3";
		break;
		case 41: selectedPitch = "G_Flat_3";
		break;
		case 42: selectedPitch = "G_Natural_3";
		break;
		case 43: selectedPitch = "G_Sharp_3";
		break;
		case 44: selectedPitch = "A_Flat_3";
		break;
		case 45: selectedPitch = "A_Natural_3";
		break;
		case 46: selectedPitch = "A_Sharp_3";
		break;
		case 47: selectedPitch = "B_Flat_3";
		break;
		case 48: selectedPitch = "B_Natural_3";
		break;
		case 49: selectedPitch = "C_Natural_4";
		break;
		case 50: selectedPitch = "C_Sharp_4";
		break;
		case 51: selectedPitch = "D_Flat_4";
		break;
		case 52: selectedPitch = "D_Natural_4";
		break;
		case 53: selectedPitch = "D_Sharp_4";
		break;
		case 54: selectedPitch = "E_Flat_4";
		break;
		case 55: selectedPitch = "E_Natural_4";
		break;
		case 56: selectedPitch = "F_Natural_4";
		break;
		case 57: selectedPitch = "F_Sharp_4";
		break;
		case 58: selectedPitch = "G_Flat_4";
		break;
		case 59: selectedPitch = "G_Natural_4";
		break;
		}
		System.out.println(selectedPitch);
		return selectedPitch;
	}
}
